name: Check OpenAPI specs have been generated

on: [pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  update-specs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check if specs have changed
      run: |
        ./scripts/create-specs.sh
        ./scripts/check-specs.sh

        exit_code=$?
        
        echo "Exit code: $exit_code"
        
        if [ $exit_code -ne 0 ]; then
          echo "Specs have changed, please run 'create-specs' and commit the changes"
          exit 1
        fi
